### ISSUE TITLE
Store Dicom

### ISSUE THREAD

**Issue by mertyergin** [teffalump/orthanc-rest-client#11]
Hi,

I tried to send dicom with Orthanc's `store_modality` function. I got 400 bad request error. This function takes `dcm` and `data`
 properties. I didn't fully understand the `data` parameter. Can you provide an example

Thanks

**Comment by teffalump** [comment]
Hi --- sorry for the really late response.

https://api.orthanc-server.com/#tag/Networking/paths/~1modalities~1{id}~1store/post

There is the API. The `dicom` parameter is the id and the `data` parameter takes a JSON data structure with the link above outlining the correct information. https://book.orthanc-server.com/users/rest.html#rest-store-scu has an example with cURL.

Sorry again for the late response.

**Comment by mertyergin** [comment]
No problem.

Thank you
