### ISSUE TITLE
Performing finds

### ISSUE THREAD

**Issue by joshy** [teffalump/orthanc-rest-client#2]
Hi,

is there any support for [performing finds](http://book.orthanc-server.com/users/rest.html#performing-finds-within-orthanc)?

Thanks,
Joshy

**Comment by teffalump** [comment]
Yes.
search_dict = {'Level': 'Patient', 'Query': ...}
orthanc.find(search_dict)

**Comment by teffalump** [comment]
I need to work on the documentation. Lol.

**Comment by joshy** [comment]
Cool, thanks!
