### ISSUE TITLE
Converting instance to a dcm file

### ISSUE THREAD

**Issue by omartoutounji** [teffalump/orthanc-rest-client#4]
Hello,

Is there any way to convert an instance into a .dcm file? I am trying to do the code below but 'get_file()' doesn't exist.
```python
    query = {'Level': 'Instance',
                'Query': {'PatientName': data.get('case')},
            }
    for id in orthanc.find(query):
        dicom = orthanc.get_instance(id)
        # orthanc.get_file(dicom) - then convert to a file locally using OS or something
```

In other words, I am trying to do this as mentioned in https://book.orthanc-server.com/users/rest.html#accessing-the-dicom-fields-of-an-instance-as-a-json-file

```
$ curl http://localhost:8042/instances/e668dcbf-8829a100-c0bd203b-41e404d9-c533f3d4/file > Instance.dcm
```

**Comment by omartoutounji** [comment]
I am trying to do this as mentioned in https://book.orthanc-server.com/users/rest.html#accessing-the-dicom-fields-of-an-instance-as-a-json-file

```
$ curl http://localhost:8042/instances/e668dcbf-8829a100-c0bd203b-41e404d9-c533f3d4/file > Instance.dcm
```

**Comment by teffalump** [comment]
@omartoutounji Hiya! Great question. There is a method to get the file:

    orthanc.get_instance_file(id)

Which will return a generator.

To mimic the curl behavior, you can do something like this:

    with open('test.dcm', 'wb') as dcm:
        for chunk in orthanc.get_instance_file(<id>):
            dcm.write(chunk)

Hope that helps. It is truly my fault for not documenting better but hopefully I can start soon.

**Comment by omartoutounji** [comment]
@teffalump thank you so much, it worked beautifully! 

I actually really like ```orthanc_rest_client```'s documentation, it's simple and straight to the point which is a great thing because a lot of well-known api's struggle with just that. As for feedback, I think it only needs like an ```Advanced``` section that documents methods like ```orthanc.get_instance_file(id)``` or use-cases like this issue.

I wrapped a method around your code for others to use and get started quickly when they visit this issue:
```python
# create_dcm_file(instance_id) produces a dcm file and puts it in your current working directory
def create_dcm_file(instance_id):
    fileName = instance_id + ".dcm"
    with open(fileName, 'wb') as dcm:
     for chunk in orthanc.get_instance_file(instance_id):
         dcm.write(chunk)
```

**Comment by teffalump** [comment]
@omartoutounji Thanks for the code and suggestions! I'll assuredly add your code to the documentation! =-)
