### ISSUE TITLE
some guidance

### ISSUE THREAD

**Issue by ludicludo** [teffalump/orthanc-rest-client#6]
Thank you very much for this developpement. I am struggling to get it work properly though.

What is the `id` you are referring to ? 
this snippet
``` python
query_pat = {'Level': 'Patient',
            'Query': {'PatientName': 'test*'},
        }

id = orthanc.find(query_pat)
print(id)
orthanc.get_patient_series(id[0])
```
gives me a **keyword error** message. `KeyError: 'id'`
and some warnings 
> ... site-packages\orthanc_rest_client\orthanc.py:33: RuntimeWarning: An unknown path kwarg was supplied to patients/{id}/series/. kwargs supplied: {'path_kwargs': {'id': 'cf74b893-0c49f5f4-c491da1d-b7485ee8-9a3ea1e1'}}
  return function(self, *args, **kwargs)

**Comment by ludicludo** [comment]
Hi again,
I get the latest version from github instead of one from pypi and suddenly it worked.
Sorry for bothering.

**Comment by teffalump** [comment]
@ludicludo Thanks for the interest! I did redo some of the functions because apiron function calling changed. I'll try to update the pypi version to see if that works for you, too. On a side note, I would suggest not using `id` as a variable name. Thanks again!
