### ISSUE TITLE
SSL with no verification

### ISSUE THREAD

**Issue by aydindemircioglu** [teffalump/orthanc-rest-client#7]
hi, thanks for the package.

i want to communicate with a personal, "off-the-internet" server which unfortunately has no kind of SSL certificate, but still communicates with https. i get a handshake error:

---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
    452             try:
--> 453                 cnx.do_handshake()
    454             except OpenSSL.SSL.WantReadError:

/usr/lib/python3/dist-packages/OpenSSL/SSL.py in do_handshake(self)
   1807         result = _lib.SSL_do_handshake(self._ssl)
-> 1808         self._raise_ssl_error(self._ssl, result)
   1809 

/usr/lib/python3/dist-packages/OpenSSL/SSL.py in _raise_ssl_error(self, ssl, result)
   1547         else:
-> 1548             _raise_current_error()
   1549 

/usr/lib/python3/dist-packages/OpenSSL/_util.py in exception_from_error_queue(exception_type)
     53 
---> 54     raise exception_type(errors)
     55 

Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    342         try:
--> 343             self._validate_conn(conn)
    344         except (SocketTimeout, BaseSSLError) as e:

/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
    838         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
--> 839             conn.connect()
    840 

/usr/local/lib/python3.6/dist-packages/urllib3/connection.py in connect(self)
    343             server_hostname=server_hostname,
--> 344             ssl_context=context)
    345 

/usr/local/lib/python3.6/dist-packages/urllib3/util/ssl_.py in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context, ca_cert_dir)
    356 
--> 357     return context.wrap_socket(sock)
    358 

/usr/local/lib/python3.6/dist-packages/urllib3/contrib/pyopenssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
    458             except OpenSSL.SSL.Error as e:
--> 459                 raise ssl.SSLError('bad handshake: %r' % e)
    460             break

SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    666                                 release_conn=release_conn, body_pos=body_pos,
--> 667                                 **response_kw)
    668 

/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    637             retries = retries.increment(method, url, error=e, _pool=self,
--> 638                                         _stacktrace=sys.exc_info()[2])
    639             retries.sleep()

/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    397         if new_retry.is_exhausted():
--> 398             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    399 

MaxRetryError: HTTPSConnectionPool(host='X.X.X.X, port=8042): Max retries exceeded with url: /patients/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

During handling of the above exception, another exception occurred:

SSLError                                  Traceback (most recent call last)
<ipython-input-20-0b231f7d15f6> in <module>()
----> 1 orthanc.get_patients()

/usr/local/lib/python3.6/dist-packages/beren/orthanc.py in get_patients(self, expand, since, limit, params, **kwargs)
    490             kwargs["params"] = params
    491         kwargs["auth"] = kwargs.get("auth", self._auth)
--> 492         return self.patients.patients(**kwargs)
    493 
    494     def get_patient(self, id_, **kwargs):

/usr/local/lib/python3.6/dist-packages/apiron/client.py in call(service, endpoint, method, session, params, data, files, json, headers, cookies, auth, encoding, retry_spec, timeout_spec, logger, allow_redirects, return_raw_response_object, **kwargs)
    246         timeout=(timeout_spec.connection_timeout, timeout_spec.read_timeout),
    247         stream=getattr(endpoint, "streaming", False),
--> 248         allow_redirects=allow_redirects,
    249     )
    250 

/usr/local/lib/python3.6/dist-packages/requests/sessions.py in send(self, request, **kwargs)
    641 
    642         # Send the request
--> 643         r = adapter.send(request, **kwargs)
    644 
    645         # Total elapsed time of the request (approximately)

/usr/local/lib/python3.6/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    512             if isinstance(e.reason, _SSLError):
    513                 # This branch is for urllib3 v1.22 and later.
--> 514                 raise SSLError(e, request=request)
    515 
    516             raise ConnectionError(e, request=request)

SSLError: HTTPSConnectionPool(host='X.X.X.X', port=8042): Max retries exceeded with url: /patients/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

is there a way to go around this problem? or is it possible to add a  "verify" argument to Orthanc? (possibly aprion needs the corresponding change)

thanks

**Comment by teffalump** [comment]
Previously, you could pass `verify=False` to any function which should then ultimately be passed to `requests` library. Apiron changed that to not allow directly passing those in more recent versions.

Instead, I believe you can do:

    # New session
    import requests
    s = requests.session.Session()

    # Disable certificate checking
    s.verify = False

    # Use new session
    orthanc.get_patients(session=s) 

Tell me if that works and I can add it to the README.

**Comment by aydindemircioglu** [comment]
thanks, will try out this week and report back!

**Comment by aydindemircioglu** [comment]
thanks, that worked! though i have now another issue.. ;)

**Comment by iamatsundere** [comment]
I've tried this but it doesn't work

```
from beren import Orthanc
import requests

s = requests.session.Session()
oc2 = Orthanc(settings.ORTHANC_API_URI)


oc2.add_instance(session=s, normalized_bytes)
```

because there is no `session` parameter in function.

**Comment by teffalump** [comment]
Thanks for using the library. 

Should be able to do

    s = requests.sessions.Session()
    oc2.add_instance(normalized_bytes, session=s)

You need to switch the argument order. The session is passed to `apiron` (and ultimately `requests`) in the function definition with `**kwargs`

**Comment by iamatsundere** [comment]
Thanks for reply :D I will try and response ASAP!

**Comment by iamatsundere** [comment]
It worked, my thanks!
