### ISSUE TITLE
Timeout when getting patients

### ISSUE THREAD

**Issue by aydindemircioglu** [teffalump/orthanc-rest-client#8]
when i try to obtain all patients from orthanc, i get a timeout error.
the orthanc server hosts quite a large number of patients, and orthanc is running on a single-core VM, so it might take much more than the 3 seconds default timeout. 
how to increase the timeout?
(sorry, i am still not an REST expert, if this issue is a simple extra argument somewhere)

**Comment by teffalump** [comment]
Good to see the other issue worked. Yeah, `apiron` has a good many options you can use to manage the [connection](https://apiron.readthedocs.io/en/latest/advanced-usage.html). Also the [code](https://github.com/ithaka/apiron/blob/44348b630ac8c8c226e1c289c76430f567d61e10/src/apiron/client.py#L145).

For an example:

    from apiron import Timeout
    t = Timeout(read_timeout=6, connection_timeout=1) # increase until it works
    orthanc.slow_endpoint(timeout_spec=t)

You can increase the timeouts as required by trial and error.

**Comment by aydindemircioglu** [comment]
thanks a lot! works fine!

(just in case someone else has similar problems and because i was puzzled about it:
i think you mean orthanc_slow_endpoint and not orthanc.slow_endpoint() ;) ;))
