### ISSUE TITLE
'Orthanc' object has no attribute 'slow_endpoint'

### ISSUE THREAD

**Issue by buptxiaofeng** [teffalump/orthanc-rest-client#9]
How to config a new timeout?  I can not find slow_endpoint in the source code.

**Comment by teffalump** [comment]
I'll change the README to be clearer, but `slow_endpoint` is simply a placeholder for any of the endpoints. For example, you could use `get_patients` instead.

Updated the README ed21eab

**Comment by buptxiaofeng** [comment]
@teffalump  Thanks for your reply.
